@Content-Type = application/json

### 测试取消订单接口
POST http://localhost:8000/users/register
Content-Type: {{Content-Type}}

{
    "user_name":"韩梅梅",
    "password":"123456"
}

### 测试提交订单接口
POST http://localhost:8000/orders
Content-Type: {{Content-Type}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJfbmFtZSI6IuWwj-W8oCIsImlzX2FkbWluIjpmYWxzZSwiaWF0IjoxNjk0NTgyNTgzLCJleHAiOjE2OTQ2Njg5ODN9.zTQMKb5mZntVo1eMcqCKT-DM1rC1oypFDZHqzz8OcqU

{
    "address_id":1,
    "goods_info":"[{},{}]",
    "total":"111.00"
}
